name: Build-Prod

on:
  workflow_call: 

jobs:
  build-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build dev application
        run: echo ceci est un build avec les config de prod

