name: Build


on:
  push:
    branches:
      - main
      - release/**
      - feature/**

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build_dev.yml
    secrets: inherit


  test:
    needs: call-build-workflow
    runs-on: ubuntu-latest

    steps:

      - name: Test application
        run: echo ceci est un build
